import mlflow
import matplotlib.pyplot as plt


def log_plot_to_mlflow(plot_func, filename="plot.png", **kwargs):
    """
    Saves a plot generated by a function to MLflow.

    Parameters:
        plot_func (callable): Function that generates the plot using matplotlib.
        filename (str): Name of the file to save the plot.
        **kwargs: Additional parameters for the plot function.
    """
    # Gera o gráfico
    plot_func(**kwargs)

    # Salva o gráfico localmente
    filepath = f"./{filename}"
    plt.savefig(filepath)
    plt.close()

    # Registra o gráfico como artefato no MLflow
    mlflow.log_artifact(filepath)
    print(f"Gráfico salvo como artefato: {filepath}")