data_collection:
  yfinance_ticker: "BTC-USD"
  yfinance_period: "10y"

model:
  framework: "pytorch"
  hidden_layer_size: 350
  num_layers: 3
  dropout: 0.35

training:
  seq_length: 60
  epochs: 200
  learning_rate: 0.0001
  weight_decay: 1e-5
  batch_size: 32

scheduler:
  type: "step"
  step_size: 40
  gamma: 0.75
  patience: 10
  factor: 0.3
  cyclic_base_lr: 1e-5
  cyclic_max_lr: 0.0005
  step_size_up: 10
  t_max: 50

early_stopping:
  patience: 20

prediction:
  future_days: 7