services:
  api:
    build: .
    container_name: btc_prediction_api
    ports:
      - "8080:8080"
    networks:
      - api_network

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - api_network

  grafana:
    image: grafana/grafana:8.5.5
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - api_network
    depends_on:
      - prometheus

networks:
  api_network:
    driver: bridge
